### ISSUE TITLE
publish code coverage for unit tests

### ISSUE THREAD

**Issue by dhebbeker** [dhebbeker/task-tracker#55]
See [WIP](https://github.com/Task-Tracker-Systems/Task-Tracker-Device/blob/b15d1c66f6a9f15ea43c1113b92add38f36187d3/platformio.ini#L54).

Acceptance criteria:

- for all executed unit tests the code coverage shall be published as HTML
- the code coverage shall be prominently visible in each pull request
- the intention is to motivate a high code coverage before requesting a merge

Depends on: 

- #54

**Comment by dhebbeker** [comment]
The code coverage (GCDA and GCNO files) is already generated. The HTML report is missing.

This may be helpful ([generated via ChatGPT](https://chat.openai.com/share/895c813d-2d6e-4139-92f0-18875e931698)):

```yaml
name: Unit Test with Coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PlatformIO
      run: sudo apt-get install -y python3-pip && pip3 install -U platformio

    - name: Install lcov
      run: sudo apt-get install lcov

    - name: Run Unit Tests with Coverage
      run: |
        platformio test --environment <your_environment> --project-option="build_flags=-ftest-coverage -fprofile-arcs"

    - name: Generate Coverage HTML Report
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage-html

    - name: Upload Coverage HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-html

```
